### ISSUE TITLE
class `Router` is not exposed

### ISSUE THREAD

**Issue by juliuste** [akheron/typera#164]
Hey (: First of all, thank you very much for developing this great library!

When trying out `typera-express`, in preparation to be used in combination with `typera-openapi`, I came across the following issue. When running this code

```ts
import {
  Response, Route, route, router,
} from 'typera-express';

const someRoute: Route<
Response.Ok<string> | Response.BadRequest<void>
> = route
  .get('/something/:id')
  .handler(async (request) => {
    const { id } = request.routeParams;
    if (id.length === 0) return Response.badRequest();
    return Response.ok(id);
  });

export default router(someRoute);
```

the typescript compiler reports `Default export of the module has or is using private name 'Router'.` as an error on the `export default`. **[Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwFBzgJQKYGdIDssYA06EArjEXFGRcdeRlIUgL5wBm1IcA5DAJ5hGAQwC0GAB5go2LDwDcSJAGMI+eFgggMaGhgBcJBgB4kmHGoIA6APIBrY1hhRguAOYA+OAB902PNYAQsIAJpgAjqTYMMYAbhDAIR5IXgC8VHoocFZuGDAAFDwA9JraMAAWrm5F+ok8AJRZVuXCuCEANoz5wlj8uMpw+TKR0fVwqV7IqKiq6ohwiXBs6cNRTlb0FAAKwlDCIFiK0wvsg4lWne4V46npAAxjMjCkULh+FvgYVgBGoRFrBXqR2mTxeb3MAS+EDs+USQKyLHhSEkkFgcBCGHYwlI7Xgmy6pR0enhQA) is a typescript playground to reproduce the issue.**

This could probably be fixed by exposing the `Router` class in the library, but on the other hand, I'm wondering if you see anything unusual in what I did above, since `typera-openapi` (which requires the default-exported router) seems to work fine for other people (?).

**Comment by akheron** [comment]
Thanks for the report!

You only get the error if you have the `"declaration": true` compiler option in your `tsconfig.json`. Removing it from the playground you linked fixes the problem, and that's why it has worked for other people. TypeScript only needs to be able to reference all the used types in compilation output in `.d.ts` files, so this makes sense.

**Comment by akheron** [comment]
Fix released in v2.4.1

**Comment by juliuste** [comment]
Thanks for the incredibly fast fix & explanation! I'd be happy to sponsor you one or two coffees, do you have a paypal or something similar?

**Comment by akheron** [comment]
Thanks, I really appreciate the gesture! Unfortunately it's _really complicated_ to accept donations for a person like me who lives in Finland, due to taxation and complex legislation.

Typera, or any of my open source projects, have gone forward the most when people have used them and reported issues or suggested features, and exactly that is the best donation you can give right now 💎
