### ISSUE TITLE
Will there be custom path capture methods in 2.0?

### ISSUE THREAD

**Issue by frabbit** [akheron/typera#31]
Hi @akheron , 

I really like your library and i'm currently using my own path capture methods based on iots codecs for branded types etc.. I saw your introduction of path patterns for 2.0 and now i fear that my custom methods will not work in the future. Is it planned to add custom methods like `int` to parse path patterns?

**Comment by akheron** [comment]
Hmm, I see. There was built-in support to capture strings and ints, and the new path capturing has those too. It didn't cross my mind that someone might have implemented their own capturers.

I think it might be possible to add more transforms like `(int)` on the type-level, but it's far from trivial. It might also be possible to bring support for the old capturers back.

**Comment by akheron** [comment]
Would it be cumbersome to do your captures as strings and then transform them in the route handler body? Or I guess it could be done in a middleware function, too. Not sure if the types currently expose captured route params to the middleware, though, but that shouldn't be hard to add.

**Comment by frabbit** [comment]
hmm, sure it would be possible but i would find it cumbersome and less expressive. The old implementation allowed determining the Pathtype directly from the path definition. I use branded types like Uuid or for example. I actually really like that i can reuse all my codecs for all parts of the request (header, body, query, path).

**Comment by akheron** [comment]
How would it feel to you if custom path captures were implemented like this:

```typescript
const bool: URL.PathTransform<boolean> = (value) =>
  value === 'true' ? Either.right(true)
  : value === 'false' ? Either.right(false)
  : Either.left('something?')

const otherType: URL.PathTransform<...> = /* something else */

const myRoute = route.usePathTransforms({ bool, otherType })

const addUser = myRoute
  .post('/users/:isSuperuser(bool)/:somethingElse(otherType)')
  .handler(async (request) => {
   ...
})
```

That is, you could register new path transforms by name and use them by name in the path captures. I made a quick type-level PoC on this yesterday, and it seems doable to me, and not even that hard actually.

IIRC, the v1 path transforms allowed specifying a custom regexp to be used in the path string. Not sure if this is useful anymore, do you have an opinion?

Another open thing is should the path transform be able to return custom responses, or is it always a 404 Not Found if the path transform doesn't match. If it's always 404, then the transform function could just return an `Option` instead of `Either`.

**Comment by akheron** [comment]
Added support for custom route parameter conversions like proposed above, but a slightly different terminology. If you have time to check it out, let me know what you think!

**Comment by frabbit** [comment]
@akheron that looks great, thanks a lot. I'll let you know if i run into any issues here.
